apiVersion: v1
kind: Service
metadata:
  name: msauth
  namespace: sit
  labels:
    app: msauth
spec:
  selector:
    app: msauth
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8998